### ISSUE TITLE
Stopped giving me bitches ever since the latest update

### ISSUE THREAD

**Issue by AD1340** [Ty1991twitter/Sonic-Mania-and-RSDKv5-Decompilation-Emscripten#1]
please fix this ever since I updated it stopped generating bitches for me and says "b-generator.dll has not been found" every time I try to open it

**Comment by AD1340** [comment]
im gonna see if I can find the file at https://www.dll-files.com/

**Comment by Ty1991twitter** [comment]
It's only because you have small-dick.dll installed. You need big-dick.dll to actually use the generator.

**Comment by AD1340** [comment]
> It's only because you have small-dick.dll installed. You need big-dick.dll to actually use the generator.

thx ill look for big-dick.dll
